<?php

namespace PISystems\ExactOnline\Util;

use PISystems\ExactOnline\Model\AddableStreamInterface;
use PISystems\ExactOnline\Model\ExactAppConfigurationInterface;

/**
 * Be careful with this information if this is leaked, not only will the app be compromised.
 *
 * >> But __ALL THE ADMINISTRATIONS THAT THIS APP HAS ACCESS TO__ <<
 */
final class OnDemandAppConfigurationLoader implements ExactAppConfigurationInterface
{
    private ?DirectExactAppConfiguration $_config = null;

    /**
     * @var \Closure<DirectExactAppConfiguration> $handler
     */
    public function __construct(
        #[\SensitiveParameter]
        private readonly \Closure $handler
    ) {}

    protected function config() : DirectExactAppConfiguration
    {
        return $this->_config ??= (function() {
            $handler = $this->handler;
            $config =  $handler();
            if (!$config instanceof DirectExactAppConfiguration) {
                throw new \RuntimeException('Client details generated by '. OnDemandAppConfigurationLoader::class.'->handler should be an instance of DirectExactAppConfiguration');
            }
            return $config;
        })();

    }

    public function addClientDetails(
        AddableStreamInterface $stream,
        int            $elements = self::CLIENT_ID | self::CLIENT_SECRET | self::CLIENT_REDIRECT_URI
    ) : AddableStreamInterface
    {
        $config = $this->config();
        return $config->addClientDetails($stream, $elements);
    }

    public function clientId(): string
    {
        return $this->config()->clientId();
    }

    public function redirectUri(): string
    {
        return $this->config()->redirectUri();
    }


}